# Generated by Django 5.2 on 2025-10-27 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoffer',
            name='social_network',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('vk', 'VK'), ('telegram', 'Telegram')], default='instagram', max_length=30),
        ),
        migrations.AlterField(
            model_name='adoffer',
            name='blogger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='bloggers.blogger'),
        ),
    ]
