# Generated by Django 5.2 on 2025-10-27 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers', '0002_adoffer_social_network_alter_adoffer_blogger'),
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_bloggers', to='managers.manager', verbose_name='Менеджер'),
        ),
    ]
