# Generated by Django 5.2 on 2025-10-28 00:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloggers", "0003_blogger_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoffer",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="adoffer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
