# Generated by Django 5.2 on 2025-10-28 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0005_alter_order_user"),
        ("managers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="managerorder",
            name="personal_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_manager_orders",
                to="ads.order",
            ),
        ),
    ]
