# Generated by Django 5.2 on 2025-10-28 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0002_managerorder_personal_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="managerorder",
            name="personal_order",
        ),
    ]
