# Generated by Django 5.2.6 on 2025-10-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_order_ad_type_order_budget_order_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="deadline",
            field=models.PositiveIntegerField(
                blank=True, help_text="Срок выполнения в днях", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="requirements",
            field=models.TextField(blank=True, help_text="Дополнительные требования"),
        ),
    ]
