# Generated by Django 5.2 on 2025-10-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin"), ("manager", "Manager")],
                default="user",
                max_length=20,
            ),
        ),
    ]
